/**
 * Animated splash screen.
 *
 * Takes over seamlessly from the native BootSplash (no flicker), plays a
 * "pop then zoom-out + fade" animation on the logo, then reveals the app.
 *
 * Requires the assets generated by:
 *   bunx react-native-bootsplash generate <logo> --assets-output=assets/bootsplash ...
 */

import { useRef } from 'react';
import { Animated, Easing, StyleSheet } from 'react-native';
import BootSplash from 'react-native-bootsplash';

type Props = {
  onAnimationEnd: () => void;
};

function AnimatedBootSplash({ onAnimationEnd }: Props) {
  const opacity = useRef(new Animated.Value(1)).current;
  const scale = useRef(new Animated.Value(0.8)).current;
  const translateY = useRef(new Animated.Value(0)).current;

  const { container, logo } = BootSplash.useHideAnimation({
    manifest: require('../assets/bootsplash/manifest.json'),
    logo: require('../assets/bootsplash/logo.png'),
    animate: () => {
      Animated.sequence([
        // 1. Logo pops in with a springy bounce.
        Animated.spring(scale, {
          toValue: 1,
          useNativeDriver: true,
          friction: 4,
          tension: 80,
        }),
        Animated.delay(200),
        // 2. Logo lifts + zooms out while the whole screen fades away.
        Animated.parallel([
          Animated.timing(translateY, {
            toValue: -40,
            duration: 450,
            easing: Easing.in(Easing.ease),
            useNativeDriver: true,
          }),
          Animated.timing(scale, {
            toValue: 8,
            duration: 450,
            easing: Easing.in(Easing.cubic),
            useNativeDriver: true,
          }),
          Animated.timing(opacity, {
            toValue: 0,
            duration: 450,
            useNativeDriver: true,
          }),
        ]),
      ]).start(onAnimationEnd);
    },
  });

  return (
    <Animated.View
      {...container}
      style={[container.style, styles.container, { opacity }]}>
      <Animated.Image
        {...logo}
        style={[logo.style, { transform: [{ translateY }, { scale }] }]}
      />
    </Animated.View>
  );
}

const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default AnimatedBootSplash;
