/**
 * ComponentLabScreen — DEV-ONLY walkthrough host for Story 18-3 (spec D7).
 * Never imported outside an `if (__DEV__)` branch (the RootNavigator
 * require sits inside the gate), so Metro DCE kills it from release
 * bundles — release-checked by scripts/verify-no-component-lab.js (android:build:release).
 *
 * Two sections:
 *  (a) the PROOF month — canned rows GENERATED by mapping the exhaustive
 *      12-key list through `dayStatusVisual` (never hand-written
 *      colours/icons: a table drift breaks here loudly instead of
 *      silently mis-rendering). All 12 statuses render at real cell size —
 *      the AC-1 same-hue distinctness evidence source (screenshots come
 *      from THIS month only, no production data). Its sheet passes the
 *      read-only posture (18-4 D1): a write against canned data + a
 *      placeholder UUID would 404 no-leak — a baffling error on fake data.
 *  (b) a REAL month — employee picker (id→name from the MMKV-hydrated
 *      ProfileTechnician roster; the wire carries no employeeName) + month
 *      nav through `useMonthStatuses` (RealMonthPane), whose cells open the
 *      REAL DayDetailSheet against production data — wired END-TO-END for
 *      18-4: `correctDay` writes, the pane's non-clearing refresh repaints
 *      the cell in place (D5).
 *
 * 19-5/19-6 replace this screen as the real hosts; the lab (and its dev
 * row on AttendanceHome) retires with them.
 */
import { useMemo, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Select } from '../../../components/ui';
import { colors, fontSize, spacing, weight } from '../../../theme';
import ScreenHeader from '../offices/ScreenHeader';
import { useTechnicians } from '../../technicians/useTechnicians';
import type { RootStackParamList } from '../../../navigation/types';
import type { DayStatusKey, DayStatusRow } from '../../../services/resources/attendanceDayStatus';
import { correctDay } from '../../../services/resources/attendanceCorrections';
import type { CorrectionWriteBody } from '../../../services/resources/attendanceCorrections';
import { DAY_STATUS_VISUALS } from './dayStatusVisual';
import { MonthCalendar } from './MonthCalendar';
import { DayDetailSheet } from './DayDetailSheet';
import { RealMonthPane, type RealMonthReport } from './RealMonthPane';
import { shiftYearMonth } from '../monthly/monthlyModel';

/** Release-bundle grep target (the build step asserts this string is
 *  ABSENT from release builds — the __DEV__ require is the only importer). */
export const COMPONENT_LAB_MARKER = 'component-lab-18-3';

const PROOF_MONTH = '2026-03'; // a fixed canned month — never production data
/** The proof month's canned "wire today" (its last day): every proof day
 *  is date-correctable, so the read-only posture — not the date gate — is
 *  what suppresses the Correct entry (asserted by the sheet suite too). */
const PROOF_TODAY = '2026-03-31';
const LAB_EMPLOYEE_ID = '00000000-0000-0000-0000-000000000000';

/** The lab's own starting month — scaffolding, so the device clock is fine
 *  here (the today RING stays wire-fed; it just renders once data lands). */
function initialYearMonth(): string {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
}

/** The canned month: day N carries the Nth wire key, generated through the
 *  ONE table. One day carries a latestCorrection so the sheet's quoted
 *  note renders; its history fetch answers 404 (lab scope) — an honest
 *  look at the error posture, never fake history data. */
function buildProofDays(): Map<string, DayStatusRow> {
  const keys = Object.keys(DAY_STATUS_VISUALS) as DayStatusKey[];
  const days = new Map<string, DayStatusRow>();
  keys.forEach((status, index) => {
    const workDate = `${PROOF_MONTH}-${String(index + 1).padStart(2, '0')}`;
    days.set(workDate, {
      workDate,
      status,
      lateMinutes: status === 'present' ? 22 : null,
      isLate: status === 'present',
      earlyCheckoutMinutes: null,
      earlyCheckout: false,
      workedMinutes: status === 'present' ? 488 : null,
      daysWorked: 0,
      leaveCredit: 0,
      workedOnHolidayCredit: 0,
      isWeeklyOff: status === 'weekly_off',
      holidayName: status === 'holiday' ? 'Sample holiday' : null,
      isWorkingDay: status !== 'weekly_off' && status !== 'holiday',
      officeId: null,
      officeName: status === 'present' ? 'Lab office' : null,
      checkinAt: null,
      checkoutAt: null,
      checkinSource: null,
      checkoutSource: null,
      checkinDistanceM: null,
      checkoutDistanceM: null,
      markers: [],
      ...(status === 'present'
        ? {
            latestCorrection: {
              correctedAt: `${PROOF_MONTH}-15T10:00:00+05:30`,
              actorName: 'Lab owner',
              note: 'Checkout was forgotten — corrected to present.',
              oldValue: {
                status: 'checkout_missing',
                checkinAt: null,
                checkoutAt: null,
              },
              newValue: { status: 'present', checkinAt: null, checkoutAt: null },
            },
          }
        : {}),
    });
  });
  return days;
}

type Props = NativeStackScreenProps<RootStackParamList, 'ComponentLab'>;

export default function ComponentLabScreen({ navigation }: Props) {
  const { technicians } = useTechnicians();
  // Roster read is MMKV-synchronous — the first employee can start picked.
  const [employeeId, setEmployeeId] = useState<string | null>(
    technicians[0]?.id ?? null,
  );
  const [yearMonth, setYearMonth] = useState(initialYearMonth);
  const [proofPick, setProofPick] = useState<string | null>(null);
  const [realPick, setRealPick] = useState<string | null>(null);

  // Proof month (canned, static).
  const proofDays = useMemo(buildProofDays, []);

  // The real pane reports its rows/today/refresh back for the sheet (data
  // ownership stays in the pane; the parent holds the picked day only).
  const [realMonth, setRealMonth] = useState<RealMonthReport | null>(null);

  return (
    <SafeAreaView style={styles.root} edges={['top']}>
      <ScreenHeader title="Component lab (dev)" onBack={() => navigation.goBack()} />

      <View style={styles.body} testID={COMPONENT_LAB_MARKER}>
        <Text style={styles.sectionTitle}>Proof month — all 12 statuses</Text>
        <MonthCalendar
          yearMonth={PROOF_MONTH}
          days={proofDays}
          today={null}
          onPickDate={setProofPick}
        />
        <Text style={styles.caption}>
          Same-hue pairs must read as different glyphs. Canned data only.
        </Text>

        <Text style={styles.sectionTitle}>Real month</Text>
        <Select
          label="Employee"
          value={employeeId ?? undefined}
          onChange={setEmployeeId}
          options={technicians.map(t => ({ value: t.id, label: t.name }))}
        />
        {employeeId == null ? (
          <Text style={styles.caption}>
            No employees in the roster yet — the real month needs one.
          </Text>
        ) : (
          <RealMonthPane
            employeeId={employeeId}
            yearMonth={yearMonth}
            onShiftMonth={delta => setYearMonth(shiftYearMonth(yearMonth, delta))}
            onPickDay={setRealPick}
            onData={setRealMonth}
          />
        )}

        <DayDetailSheet
          visible={proofPick != null}
          workDate={proofPick}
          day={proofPick != null ? proofDays.get(proofPick) ?? null : null}
          today={PROOF_TODAY}
          scope={{ kind: 'owner', employeeId: LAB_EMPLOYEE_ID }}
          readOnly
          onClose={() => setProofPick(null)}
        />
        <DayDetailSheet
          visible={realPick != null && employeeId != null}
          workDate={realPick}
          day={
            realPick != null && realMonth
              ? realMonth.days.get(realPick) ?? null
              : null
          }
          today={realMonth?.today ?? null}
          scope={
            employeeId != null
              ? { kind: 'owner', employeeId }
              : { kind: 'me' }
          }
          onClose={() => setRealPick(null)}
          onCorrect={
            employeeId != null && realPick != null
              ? (body: CorrectionWriteBody) =>
                  correctDay(employeeId, realPick, body)
              : undefined
          }
          onCorrected={realMonth?.refresh}
        />
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.surfacePage,
  },
  body: {
    flex: 1,
    padding: spacing.s4,
    gap: spacing.s3,
  },
  sectionTitle: {
    fontSize: fontSize.lg,
    fontWeight: weight.bold,
    color: colors.textStrong,
  },
  caption: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
  },
});
