/**
 * ComponentLabScreen — DEV-ONLY walkthrough host for Story 18-3 (spec D7).
 * Never imported outside an `if (__DEV__)` branch (the RootNavigator
 * require sits inside the gate), so Metro DCE kills it from release
 * bundles — release-checked by scripts/verify-no-component-lab.js (android:build:release).
 *
 * Two sections:
 *  (a) the PROOF month — canned rows GENERATED by mapping the exhaustive
 *      12-key list through `dayStatusVisual` (never hand-written
 *      colours/icons: a table drift breaks here loudly instead of
 *      silently mis-rendering). All 12 statuses render at real cell size —
 *      the AC-1 same-hue distinctness evidence source (screenshots come
 *      from THIS month only, no production data).
 *  (b) a REAL month — employee picker (id→name from the MMKV-hydrated
 *      ProfileTechnician roster; the wire carries no employeeName) + month
 *      nav through `useMonthStatuses`, whose cells open the REAL
 *      DayDetailSheet against production data.
 *
 * 19-5/19-6 replace this screen as the real hosts; the lab (and its dev
 * row on AttendanceHome) retires with them.
 */
import { useMemo, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { ChevronLeft, ChevronRight } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Button, InlineError, Select } from '../../../components/ui';
import { colors, fontSize, spacing, weight } from '../../../theme';
import ScreenHeader from '../offices/ScreenHeader';
import { useTechnicians } from '../../technicians/useTechnicians';
import type { RootStackParamList } from '../../../navigation/types';
import type { DayStatusKey, DayStatusRow } from '../../../services/resources/attendanceDayStatus';
import { DAY_STATUS_VISUALS } from './dayStatusVisual';
import { useMonthStatuses } from './useMonthStatuses';
import { MonthCalendar } from './MonthCalendar';
import { DayDetailSheet } from './DayDetailSheet';

/** Release-bundle grep target (the build step asserts this string is
 *  ABSENT from release builds — the __DEV__ require is the only importer). */
export const COMPONENT_LAB_MARKER = 'component-lab-18-3';

const PROOF_MONTH = '2026-03'; // a fixed canned month — never production data
const LAB_EMPLOYEE_ID = '00000000-0000-0000-0000-000000000000';

/** 'YYYY-MM' shifted by n months (UTC math on the explicit 1st). */
function shiftYearMonth(yearMonth: string, months: number): string {
  const next = new Date(
    Date.UTC(Number(yearMonth.slice(0, 4)), Number(yearMonth.slice(5, 7)) - 1 + months, 1),
  );
  return `${next.getUTCFullYear()}-${String(next.getUTCMonth() + 1).padStart(2, '0')}`;
}

/** 'YYYY-MM' → "September 2026". */
function monthTitle(yearMonth: string): string {
  const names = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ];
  return `${names[Number(yearMonth.slice(5, 7)) - 1]} ${yearMonth.slice(0, 4)}`;
}

/** The lab's own starting month — scaffolding, so the device clock is fine
 *  here (the today RING stays wire-fed; it just renders once data lands). */
function initialYearMonth(): string {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
}

/** The canned month: day N carries the Nth wire key, generated through the
 *  ONE table. One day carries a latestCorrection so the sheet's quoted
 *  note renders; its history fetch answers 404 (lab scope) — an honest
 *  look at the error posture, never fake history data. */
function buildProofDays(): Map<string, DayStatusRow> {
  const keys = Object.keys(DAY_STATUS_VISUALS) as DayStatusKey[];
  const days = new Map<string, DayStatusRow>();
  keys.forEach((status, index) => {
    const workDate = `${PROOF_MONTH}-${String(index + 1).padStart(2, '0')}`;
    days.set(workDate, {
      workDate,
      status,
      lateMinutes: status === 'present' ? 22 : null,
      isLate: status === 'present',
      earlyCheckoutMinutes: null,
      earlyCheckout: false,
      workedMinutes: status === 'present' ? 488 : null,
      daysWorked: 0,
      leaveCredit: 0,
      workedOnHolidayCredit: 0,
      isWeeklyOff: status === 'weekly_off',
      holidayName: status === 'holiday' ? 'Sample holiday' : null,
      isWorkingDay: status !== 'weekly_off' && status !== 'holiday',
      officeId: null,
      officeName: status === 'present' ? 'Lab office' : null,
      checkinAt: null,
      checkoutAt: null,
      checkinSource: null,
      checkoutSource: null,
      checkinDistanceM: null,
      checkoutDistanceM: null,
      markers: [],
      ...(status === 'present'
        ? {
            latestCorrection: {
              correctedAt: `${PROOF_MONTH}-15T10:00:00+05:30`,
              actorName: 'Lab owner',
              note: 'Checkout was forgotten — corrected to present.',
              oldValue: {
                status: 'checkout_missing',
                checkinAt: null,
                checkoutAt: null,
              },
              newValue: { status: 'present', checkinAt: null, checkoutAt: null },
            },
          }
        : {}),
    });
  });
  return days;
}

type Props = NativeStackScreenProps<RootStackParamList, 'ComponentLab'>;

/** The real-data pane — mounted ONLY with a picked employee, so an empty
 *  roster never fires a wire request (the day-statuses call is real). */
function RealMonthPane({
  employeeId,
  yearMonth,
  onShiftMonth,
  onPickDay,
  onData,
}: {
  employeeId: string;
  yearMonth: string;
  onShiftMonth: (delta: number) => void;
  onPickDay: (workDate: string) => void;
  onData: (days: ReadonlyMap<string, DayStatusRow>) => void;
}) {
  const month = useMonthStatuses({
    scope: { kind: 'owner', employeeId },
    yearMonth,
  });
  // Report the rows up for the parent's sheet (an effect, never a render
  // side-effect; both deps are stable between data changes).
  useEffect(() => {
    onData(month.data);
  }, [onData, month.data]);
  return (
    <>
      <View style={styles.navRow}>
        <Pressable
          accessibilityRole="button"
          accessibilityLabel="Previous month"
          onPress={() => onShiftMonth(-1)}
          style={styles.navButton}>
          <ChevronLeft size={20} color={colors.textBody} strokeWidth={2} />
        </Pressable>
        <Text style={styles.monthLabel}>{monthTitle(yearMonth)}</Text>
        <Pressable
          accessibilityRole="button"
          accessibilityLabel="Next month"
          onPress={() => onShiftMonth(1)}
          style={styles.navButton}>
          <ChevronRight size={20} color={colors.textBody} strokeWidth={2} />
        </Pressable>
      </View>
      {month.loading ? (
        <ActivityIndicator size="large" color={colors.primary} style={styles.spinner} />
      ) : null}
      {month.error != null ? (
        <>
          <InlineError message={month.error} />
          <Button variant="secondary" size="sm" onPress={month.retry}>
            Retry
          </Button>
        </>
      ) : null}
      <MonthCalendar
        yearMonth={yearMonth}
        days={month.data}
        today={month.today}
        onPickDate={onPickDay}
      />
    </>
  );
}

export default function ComponentLabScreen({ navigation }: Props) {
  const { technicians } = useTechnicians();
  // Roster read is MMKV-synchronous — the first employee can start picked.
  const [employeeId, setEmployeeId] = useState<string | null>(
    technicians[0]?.id ?? null,
  );
  const [yearMonth, setYearMonth] = useState(initialYearMonth);
  const [proofPick, setProofPick] = useState<string | null>(null);
  const [realPick, setRealPick] = useState<string | null>(null);

  // Proof month (canned, static).
  const proofDays = useMemo(buildProofDays, []);

  // The real pane reports its rows back for the sheet (data ownership stays
  // in the pane; the parent only holds the picked day).
  const [realMonthData, setRealMonthData] =
    useState<ReadonlyMap<string, DayStatusRow> | null>(null);

  return (
    <SafeAreaView style={styles.root} edges={['top']}>
      <ScreenHeader title="Component lab (dev)" onBack={() => navigation.goBack()} />

      <View style={styles.body} testID={COMPONENT_LAB_MARKER}>
        <Text style={styles.sectionTitle}>Proof month — all 12 statuses</Text>
        <MonthCalendar
          yearMonth={PROOF_MONTH}
          days={proofDays}
          today={null}
          onPickDate={setProofPick}
        />
        <Text style={styles.caption}>
          Same-hue pairs must read as different glyphs. Canned data only.
        </Text>

        <Text style={styles.sectionTitle}>Real month</Text>
        <Select
          label="Employee"
          value={employeeId ?? undefined}
          onChange={setEmployeeId}
          options={technicians.map(t => ({ value: t.id, label: t.name }))}
        />
        {employeeId == null ? (
          <Text style={styles.caption}>
            No employees in the roster yet — the real month needs one.
          </Text>
        ) : (
          <RealMonthPane
            employeeId={employeeId}
            yearMonth={yearMonth}
            onShiftMonth={delta => setYearMonth(shiftYearMonth(yearMonth, delta))}
            onPickDay={setRealPick}
            onData={setRealMonthData}
          />
        )}

        <DayDetailSheet
          visible={proofPick != null}
          workDate={proofPick}
          day={proofPick != null ? proofDays.get(proofPick) ?? null : null}
          scope={{ kind: 'owner', employeeId: LAB_EMPLOYEE_ID }}
          onClose={() => setProofPick(null)}
        />
        <DayDetailSheet
          visible={realPick != null && employeeId != null}
          workDate={realPick}
          day={realPick != null && realMonthData ? realMonthData.get(realPick) ?? null : null}
          scope={
            employeeId != null
              ? { kind: 'owner', employeeId }
              : { kind: 'me' }
          }
          onClose={() => setRealPick(null)}
        />
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.surfacePage,
  },
  body: {
    flex: 1,
    padding: spacing.s4,
    gap: spacing.s3,
  },
  sectionTitle: {
    fontSize: fontSize.lg,
    fontWeight: weight.bold,
    color: colors.textStrong,
  },
  caption: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
  },
  navRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  navButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceCard,
    borderWidth: 1,
    borderColor: colors.borderDefault,
  },
  monthLabel: {
    fontSize: fontSize.base,
    fontWeight: weight.semibold,
    color: colors.textStrong,
  },
  spinner: {
    paddingVertical: spacing.s3,
  },
});
